name: Validate Branch Name

on:
  push:
    branches:
      - "*"

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch naming convention
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"

          if [[ ! "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix|release)\/[a-z0-9._-]+$ && "$BRANCH_NAME" != "develop" && "$BRANCH_NAME" != "main" ]]; then
            echo "❌ Nombre de rama inválido: $BRANCH_NAME"
            exit 1
          fi

          echo "✅ Nombre de rama válido: $BRANCH_NAME"
